services:
  postgres_db:
    container_name: postgres_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urls
    volumes:
      - data:/var/lib/postgresql/data
  url_shortner:
    container_name: url_shortner
    build: .
    ports:
      - 8080:8080

volumes:
  data: {}
